export interface CatalogSeedCategory {
  category: string;
  types: string[];
  brands: string[];
  eventTags: string[];
  setTags: string[];
}

export const CATALOG_SEED_DATA: CatalogSeedCategory[] = [
  {
    category: 'Chairs',
    types: [
      'Monoblock chairs',
      'Folding chairs',
      'Tiffany / Chiavari chairs',
      'Ghost chairs',
      'Bar stools',
      'Kids chairs',
      'Lounge chairs',
      'VIP sofas',
      'Ottoman seats',
      'Picnic chairs',
    ],
    brands: [
      'Lifetime Products',
      'Mandaue Foam',
      'Uratex Monoblock',
      'Polywood',
      'Flash Furniture',
      'National Public Seating',
      'HERCULES Series',
    ],
    eventTags: [
      'birthday',
      'debut',
      'wedding',
      'funeral',
      'baptism',
      'anniversary',
      'corporate',
      'reunion',
      'graduation',
      'fiesta',
    ],
    setTags: ['seating-set', 'table-set', 'reception-set', 'ceremony-set'],
  },
  {
    category: 'Tables',
    types: [
      'Round banquet tables',
      'Rectangular banquet tables',
      'Cocktail tables',
      'Bar tables',
      'Buffet tables',
      'Picnic tables',
      'Kids tables',
      'Coffee tables',
      'VIP lounge tables',
      'Folding tables',
    ],
    brands: [
      'Lifetime Products',
      'Iceberg Enterprises',
      'COSCO',
      'Meco Corporation',
      'Correll',
    ],
    eventTags: [
      'birthday',
      'debut',
      'wedding',
      'funeral',
      'baptism',
      'anniversary',
      'corporate',
      'reunion',
      'graduation',
      'fiesta',
    ],
    setTags: ['table-set', 'dining-set', 'buffet-set', 'reception-set'],
  },
  {
    category: 'Tents / Shelters',
    types: [
      'Open tent',
      'Closed tent',
      'Dome tent',
      'Frame tent',
      'High peak tent',
      'Air-conditioned tent',
      'Pagoda tent',
      'Gazebo tent',
      'Retractable tent',
      'Camping tent',
    ],
    brands: [
      'Eurmax',
      'ABCCanopy',
      'Mastertent',
      'ShelterLogic',
      'Caravan Canopy',
    ],
    eventTags: [
      'birthday',
      'debut',
      'wedding',
      'funeral',
      'baptism',
      'anniversary',
      'corporate',
      'reunion',
      'graduation',
      'fiesta',
      'seminar',
    ],
    setTags: ['tent-set', 'outdoor-set', 'booth-set', 'shelter-set'],
  },
  {
    category: 'Stage Equipment',
    types: [
      'Modular stage platforms',
      'Stage stairs',
      'Stage skirting',
      'Podium / lectern',
      'Runway / catwalk',
      'Dance floor',
      'Pipe and drape system',
      'Backdrop frames',
    ],
    brands: [
      'Staging Concepts',
      'Global Truss',
      'ProX Live Performance Gear',
      'Intellistage',
    ],
    eventTags: [
      'birthday',
      'debut',
      'wedding',
      'corporate',
      'graduation',
      'fiesta',
      'concert',
      'seminar',
    ],
    setTags: ['stage-set', 'program-set', 'performance-set'],
  },
  {
    category: 'Sound System Equipment',
    types: [
      'PA speakers',
      'Subwoofers',
      'Amplifiers',
      'Audio mixers',
      'Microphones',
      'Wireless microphone systems',
      'Karaoke systems',
      'DJ controllers',
      'Monitor speakers',
    ],
    brands: [
      'JBL',
      'QSC',
      'RCF',
      'FBT',
      'Audiocenter',
      'Behringer',
      'Yamaha',
      'Shure',
      'Sennheiser',
      'Audio-Technica',
    ],
    eventTags: [
      'birthday',
      'debut',
      'wedding',
      'corporate',
      'graduation',
      'fiesta',
      'concert',
      'seminar',
      'funeral',
    ],
    setTags: ['karaoke-set', 'sound-set', 'dj-set', 'program-set'],
  },
  {
    category: 'Lighting Equipment',
    types: [
      'PAR lights',
      'LED wash lights',
      'Moving head lights',
      'Follow spot lights',
      'Laser lights',
      'Disco lights',
      'Strobe lights',
      'String lights',
      'Chandeliers',
    ],
    brands: [
      'Chauvet DJ',
      'ADJ (American DJ)',
      'Elation Lighting',
      'Martin Professional',
    ],
    eventTags: [
      'birthday',
      'debut',
      'wedding',
      'corporate',
      'graduation',
      'fiesta',
      'concert',
      'seminar',
      'funeral',
    ],
    setTags: ['lighting-set', 'party-set', 'stage-set', 'ambience-set'],
  },
  {
    category: 'Video Equipment',
    types: [
      'LED wall panels',
      'Projectors',
      'Projection screens',
      'TVs / monitors',
      'Cameras',
      'Livestream equipment',
    ],
    brands: ['Epson', 'BenQ', 'Optoma', 'Samsung', 'LG'],
    eventTags: [
      'birthday',
      'debut',
      'wedding',
      'corporate',
      'graduation',
      'seminar',
      'concert',
      'funeral',
    ],
    setTags: ['video-set', 'presentation-set', 'livestream-set'],
  },
  {
    category: 'Catering Equipment',
    types: [
      'Chafing dishes',
      'Serving trays',
      'Plates',
      'Forks and spoons',
      'Glassware',
      'Soup bowls',
      'Wine glasses',
      'Coffee percolators',
      'Water dispensers',
    ],
    brands: ['Winco', 'Cambro', 'Vollrath'],
    eventTags: [
      'birthday',
      'debut',
      'wedding',
      'funeral',
      'baptism',
      'anniversary',
      'corporate',
      'reunion',
      'graduation',
      'fiesta',
      'seminar',
    ],
    setTags: ['catering-set', 'buffet-set', 'dining-set'],
  },
  {
    category: 'Climate / Cooling Equipment',
    types: [
      'Industrial fans',
      'Mist fans',
      'Air coolers',
      'Portable air conditioners',
    ],
    brands: ['Iwata', 'Koppel', 'Dowell'],
    eventTags: [
      'birthday',
      'debut',
      'wedding',
      'funeral',
      'baptism',
      'anniversary',
      'corporate',
      'reunion',
      'graduation',
      'fiesta',
      'seminar',
      'concert',
    ],
    setTags: ['cooling-set', 'comfort-set', 'outdoor-set'],
  },
  {
    category: 'Power Equipment',
    types: ['Generators', 'Extension cords', 'Power distribution boxes'],
    brands: ['Honda', 'Yamaha', 'Hyundai Power'],
    eventTags: [
      'birthday',
      'debut',
      'wedding',
      'funeral',
      'baptism',
      'anniversary',
      'corporate',
      'reunion',
      'graduation',
      'fiesta',
      'seminar',
      'concert',
    ],
    setTags: ['power-set', 'event-essentials-set'],
  },
  {
    category: 'Decoration Equipment',
    types: [
      'Tablecloths',
      'Chair covers',
      'Table runners',
      'Centerpieces',
      'Artificial flowers',
      'Balloon arches',
      'Wedding arches',
      'Drapes',
    ],
    brands: [],
    eventTags: [
      'birthday',
      'debut',
      'wedding',
      'funeral',
      'baptism',
      'anniversary',
      'corporate',
      'reunion',
      'graduation',
      'fiesta',
    ],
    setTags: ['decor-set', 'wedding-set', 'theme-set', 'styling-set'],
  },
  {
    category: 'Event Effects Equipment',
    types: [
      'Smoke machines',
      'Bubble machines',
      'Snow machines',
      'Confetti machines',
      'Cryo jets',
    ],
    brands: ['Antari', 'Look Solutions', 'MagicFX'],
    eventTags: [
      'birthday',
      'debut',
      'wedding',
      'fiesta',
      'concert',
      'graduation',
    ],
    setTags: ['effects-set', 'party-set', 'concert-set'],
  },
];