# syntax=docker/dockerfile:1.4
FROM node:18-alpine
WORKDIR /app

COPY package*.json ./
RUN --mount=type=cache,target=/root/.npm npm ci --omit=dev --no-audit

COPY dist ./dist

RUN mkdir -p uploads

EXPOSE 3000
CMD ["node", "dist/src/main.js"]